"""empty message

Revision ID: 2e396ea00de9
Revises: a60d3f3bcb90
Create Date: 2023-07-12 14:22:27.116417

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2e396ea00de9'
down_revision = 'a60d3f3bcb90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_toys')
    op.drop_table('checked_out_history')
    with op.batch_alter_table('toy', schema=None) as batch_op:
        batch_op.drop_column('toy_hold_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('toy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('toy_hold_number', sa.INTEGER(), autoincrement=False, nullable=True))

    op.create_table('checked_out_history',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('toy_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('checkout_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['toy_id'], ['toy.toy_id'], name='checked_out_history_toy_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name='checked_out_history_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'toy_id', name='checked_out_history_pkey')
    )
    op.create_table('users_toys',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('toy_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['toy_id'], ['toy.toy_id'], name='users_toys_toy_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name='users_toys_user_id_fkey')
    )
    # ### end Alembic commands ###
