"""empty message

Revision ID: 3681ad8b2db3
Revises: cd9fca80027f
Create Date: 2023-07-13 10:59:25.867628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3681ad8b2db3'
down_revision = 'cd9fca80027f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('check_out_history')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('check_out_history',
    sa.Column('checkout_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('toy_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('check_out_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('return_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['toy_id'], ['toy.toy_id'], name='check_out_history_toy_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name='check_out_history_user_id_fkey'),
    sa.PrimaryKeyConstraint('checkout_id', name='check_out_history_pkey')
    )
    # ### end Alembic commands ###
