"""empty message

Revision ID: 3906ed151049
Revises: 768a46a2f302
Create Date: 2023-07-11 21:00:39.083196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3906ed151049'
down_revision = '768a46a2f302'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('toy', schema=None) as batch_op:
        batch_op.alter_column('toy_status',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('toy', schema=None) as batch_op:
        batch_op.alter_column('toy_status',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    # ### end Alembic commands ###
