"""empty message

Revision ID: 5026f0b4b855
Revises: 0ec32912a1dd
Create Date: 2023-07-22 21:54:03.139568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5026f0b4b855'
down_revision = '0ec32912a1dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('toy', schema=None) as batch_op:
        batch_op.drop_column('toy_hold_number')

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reserve_date', sa.Date(), nullable=True))
        batch_op.drop_column('reserve_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reserve_status', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('reserve_date')

    with op.batch_alter_table('toy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('toy_hold_number', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
