"""empty message

Revision ID: 537c8146d94e
Revises: 5026f0b4b855
Create Date: 2023-08-01 13:28:00.215014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '537c8146d94e'
down_revision = '5026f0b4b855'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('pin')
        batch_op.drop_column('address')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('pin', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
