"""adds User Toy and Hold Models

Revision ID: 69a3716962ab
Revises: 
Create Date: 2023-07-11 20:28:53.424029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69a3716962ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('pin', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('toy',
    sa.Column('toy_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('toy_name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('age_category', sa.String(), nullable=True),
    sa.Column('toy_status', sa.Boolean(), nullable=True),
    sa.Column('toy_hold_number', sa.Integer(), nullable=True),
    sa.Column('toy_image', sa.String(), nullable=True),
    sa.Column('checked_out_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['checked_out_by'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('toy_id')
    )
    op.create_table('checked_out_history',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('toy_id', sa.Integer(), nullable=False),
    sa.Column('checkout_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['toy_id'], ['toy.toy_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'toy_id')
    )
    op.create_table('hold_toys',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('toy_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('hold_date', sa.DateTime(), nullable=True),
    sa.Column('cue_position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['toy_id'], ['toy.toy_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'toy_id')
    )
    op.create_table('users_toys',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('toy_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['toy_id'], ['toy.toy_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_toys')
    op.drop_table('hold_toys')
    op.drop_table('checked_out_history')
    op.drop_table('toy')
    op.drop_table('user')
    # ### end Alembic commands ###
