"""empty message

Revision ID: 8378c65e73b9
Revises: 35cc0df6a118
Create Date: 2023-08-02 23:34:58.343326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8378c65e73b9'
down_revision = '35cc0df6a118'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('firebase_uid',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.drop_constraint('user_firebase_uid_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_firebase_uid_key', ['firebase_uid'])
        batch_op.alter_column('firebase_uid',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)

    # ### end Alembic commands ###
