"""empty message

Revision ID: 89401030d219
Revises: f82976ff6c79
Create Date: 2023-07-11 20:58:11.124941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89401030d219'
down_revision = 'f82976ff6c79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('toy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checked_out_by_user_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('toy_checked_out_by_user_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['checked_out_by_user_id'], ['user_id'])
        batch_op.drop_column('checked_out_by_user')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('toy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checked_out_by_user', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('toy_checked_out_by_user_fkey', 'user', ['checked_out_by_user'], ['user_id'])
        batch_op.drop_column('checked_out_by_user_id')

    # ### end Alembic commands ###
