"""empty message

Revision ID: 96c4faf6f7cd
Revises: 3681ad8b2db3
Create Date: 2023-07-13 22:24:55.342996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96c4faf6f7cd'
down_revision = '3681ad8b2db3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
    sa.Column('transaction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('checkout_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.Column('reserve_status', sa.Boolean(), nullable=True),
    sa.Column('overdue_fines', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_table('transaction_association',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('toy_id', sa.Integer(), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['toy_id'], ['toy.toy_id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.transaction_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], )
    )
    with op.batch_alter_table('toy', schema=None) as batch_op:
        batch_op.drop_constraint('toy_checked_out_by_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('checked_out_by_user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('toy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checked_out_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('toy_checked_out_by_user_id_fkey', 'user', ['checked_out_by_user_id'], ['user_id'])

    op.drop_table('transaction_association')
    op.drop_table('transaction')
    # ### end Alembic commands ###
