"""empty message

Revision ID: 9d39e30e415a
Revises: 3906ed151049
Create Date: 2023-07-12 13:38:28.743602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d39e30e415a'
down_revision = '3906ed151049'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('toy', schema=None) as batch_op:
        batch_op.drop_constraint('toy_checked_out_by_user_fkey', type_='foreignkey')
        batch_op.drop_column('checked_out_by_user')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('toy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checked_out_by_user', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('toy_checked_out_by_user_fkey', 'user', ['checked_out_by_user'], ['user_id'])

    # ### end Alembic commands ###
