"""empty message

Revision ID: a60d3f3bcb90
Revises: 9d39e30e415a
Create Date: 2023-07-12 13:46:09.622072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a60d3f3bcb90'
down_revision = '9d39e30e415a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('toy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checked_out_by_user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['checked_out_by_user_id'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('toy', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('checked_out_by_user_id')

    # ### end Alembic commands ###
