"""empty message

Revision ID: a83475e3bab9
Revises: 2e396ea00de9
Create Date: 2023-07-13 00:05:28.820382

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a83475e3bab9'
down_revision = '2e396ea00de9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hold_toys')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hold_toys',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('toy_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hold_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('cue_position', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['toy_id'], ['toy.toy_id'], name='hold_toys_toy_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name='hold_toys_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'toy_id', name='hold_toys_pkey')
    )
    # ### end Alembic commands ###
