"""empty message

Revision ID: b2cc15027a4a
Revises: 8378c65e73b9
Create Date: 2023-08-07 20:02:15.147193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2cc15027a4a'
down_revision = '8378c65e73b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('toy_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('toy_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
