"""empty message

Revision ID: c220e24edc3d
Revises: 537c8146d94e
Create Date: 2023-08-02 14:16:09.137718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c220e24edc3d'
down_revision = '537c8146d94e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firebase_uid', sa.String(), nullable=True))
        batch_op.create_unique_constraint(None, ['firebase_uid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('firebase_uid')

    # ### end Alembic commands ###
