"""empty message

Revision ID: d38519f954a9
Revises: b2cc15027a4a
Create Date: 2023-08-07 20:08:42.312500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd38519f954a9'
down_revision = 'b2cc15027a4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('toy_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('toy_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
