"""empty message

Revision ID: f82976ff6c79
Revises: 69a3716962ab
Create Date: 2023-07-11 20:51:21.263793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f82976ff6c79'
down_revision = '69a3716962ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('toy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checked_out_by_user', sa.Integer(), nullable=True))
        batch_op.drop_constraint('toy_checked_out_by_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['checked_out_by_user'], ['user_id'])
        batch_op.drop_column('checked_out_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('toy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checked_out_by', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('toy_checked_out_by_fkey', 'user', ['checked_out_by'], ['user_id'])
        batch_op.drop_column('checked_out_by_user')

    # ### end Alembic commands ###
